-- Seed Services
INSERT INTO public.cms_services (slug, title, icon, desc_short, tagline, intro, benefits, deliverables, plans)
VALUES 
('web-development', 'Web Development', 'Code2', 'Fast, scalable sites and web apps built to convert.', 'Sites that load fast and sell harder', 'We build marketing sites, e-commerce stores and web apps with clean code, real performance budgets and a CMS your team can actually use.', ARRAY['Sub-2s load times on real mobile networks', 'SEO-ready structure, metadata and sitemaps', 'Editable content without calling a developer', 'Analytics and conversion tracking wired in'], ARRAY['Responsive build', 'CMS integration', 'Performance report', '30 days post-launch support'], '[{"name": "Landing", "price": "$900", "note": "one-off", "features": ["1 page", "Contact form", "Basic SEO", "2 revisions"]}, {"name": "Business Site", "price": "$2,400", "note": "one-off", "features": ["Up to 8 pages", "CMS", "SEO setup", "Speed optimisation"], "featured": true}, {"name": "Custom App", "price": "from $6,000", "note": "project", "features": ["Custom features", "Database & auth", "Integrations", "Dedicated PM"]}]'::jsonb),
('graphic-design', 'Graphic Design', 'PenTool', 'Print and social assets with a sharp, consistent voice.', 'Design that looks intentional everywhere', 'From social templates to packaging and print, we produce artwork that stays on-brand across every format and size.', ARRAY['Consistent visual voice across channels', 'Source files you own and can reuse', 'Templates your team can edit', 'Print-ready exports checked for colour'], ARRAY['Source files', 'Export pack', 'Editable templates', 'Usage notes'], '[{"name": "Single Asset", "price": "$120", "note": "per asset", "features": ["1 design", "2 revisions", "Print + digital export"]}, {"name": "Campaign Pack", "price": "$780", "note": "per campaign", "features": ["10 assets", "Social templates", "3 revisions"], "featured": true}, {"name": "Design Retainer", "price": "$1,500", "note": "/month", "features": ["Unlimited requests", "2 active at a time", "48h turnaround"]}]'::jsonb),
('identity-branding', 'Identity Branding', 'Sparkles', 'Logos, systems and guidelines that hold up everywhere.', 'A brand system, not just a logo file', 'We define how your brand looks, sounds and behaves — then document it so every future asset stays coherent.', ARRAY['Distinct positioning against competitors', 'Logo suite for every placement and size', 'Colour, type and tone documented', 'Faster future design work'], ARRAY['Logo suite', 'Colour & type system', 'Brand guidelines PDF', 'Stationery set'], '[{"name": "Starter Identity", "price": "$1,200", "note": "one-off", "features": ["Logo suite", "Colour & type", "Mini guidelines"]}, {"name": "Full Identity", "price": "$3,500", "note": "one-off", "features": ["Strategy workshop", "Full logo system", "Guidelines book", "Launch assets"], "featured": true}, {"name": "Rebrand", "price": "from $7,000", "note": "project", "features": ["Audit & research", "Naming support", "Rollout plan", "Team training"]}]'::jsonb);

-- Seed Blog Posts
INSERT INTO public.cms_posts (slug, title, excerpt, category, date, read_time, body)
VALUES
('brand-audit-checklist', 'The brand audit checklist we run before any redesign', 'Before we touch a single pixel we run a nine-point audit. Here is the exact checklist, so you can run it yourself.', 'Branding', '2026-07-28', '6 min read', ARRAY['Most redesigns fail because they start with taste instead of evidence.', 'We start with inventory...', 'Next comes consistency scoring...', 'Then we look outward...', 'Finally we test comprehension.']),
('website-speed-conversions', 'Why a one-second delay quietly costs you customers', 'Performance is a conversion feature. Here is how we get sites under one second without stripping the design.', 'Web Development', '2026-07-14', '5 min read', ARRAY['Speed is not a technical vanity metric.', 'The biggest wins are rarely exotic.', 'We serve pages rendered on the server...', 'Third-party scripts deserve special attention.', 'We treat performance as a budget...']);

-- Seed Case Studies
INSERT INTO public.cms_case_studies (slug, client, title, summary, industry, year, services, service_slugs, challenge, approach, results, quote)
VALUES
('northwind-saas', 'Northwind SaaS', 'A rebrand and rebuild that doubled demo requests', 'New identity, new marketing site and a conversion-focused demo funnel, shipped in six weeks.', 'B2B software', '2026', ARRAY['Identity Branding', 'Web Development', 'UI/UX Design'], ARRAY['identity-branding', 'web-development', 'ui-ux-design'], 'Northwind looked like a side project...', ARRAY['Ran a nine-point brand audit...', 'Built a full identity system...', 'Rebuilt the site...', 'Wired analytics...'], '[{"label": "Demo requests", "value": "+108%"}, {"label": "Load time", "value": "0.9s"}]'::jsonb, '{"text": "Mario Studio rebuilt our site and identity in six weeks.", "name": "Lina Okafor", "role": "Co-founder"}');
